### ISSUE TITLE
host "proxier.now.sh" offline?

### ISSUE THREAD

**Issue by pjpimentel** [lucianopf/proxier#5]
@lucianopf , boa tarde!

O host proxier.now.sh está offline.

Tem previsão para normalizar ou é permanente?

**Comment by pjpimentel** [comment]
![Screenshot from 2020-10-01 14-34-07](https://user-images.githubusercontent.com/11481809/94843518-2f463a80-03f3-11eb-9e88-4bcddb673703.png)

**Comment by lucianopf** [comment]
Bom dia mestre, tudo certo?

Infelizmente é sim 😢 , fui alertado pelo time da Vercel sobre o projeto estar irregular com as diretrizes da empresa e foi pedido para desligar o serviço.

Nos derem tempo para remover o proxier do `cep-promise` mas de qualquer forma o serviço precisaria ser desligado =(

**Comment by pjpimentel** [comment]
> Bom dia mestre, tudo certo?
> 
> Infelizmente é sim  , fui alertado pelo time da Vercel sobre o projeto estar irregular com as diretrizes da empresa e foi pedido para desligar o serviço.
> 
> Nos derem tempo para remover o proxier do `cep-promise` mas de qualquer forma o serviço precisaria ser desligado =(

@lucianopf valeu pela informação!
